### ISSUE TITLE
GPG Signing Problem on Alpine

### ISSUE THREAD

**Issue by amihaiemil** [g4s8/dockers#1]
I use a Maven Plugin for signing my artifacts with GPG. With the Docker image `g4s8/rultor:alpine3.10`, I get the following error in the logs: 

``gpg: signing failed: Not a tty``

After some google-ing, the Issue appears to be with Alpine, other people had it as well:
https://unix.stackexchange.com/questions/277282/gpg-key-generation-fails-on-alpine-linux-docker-image

According to the response there, I added the environment variable: ``export GPG_TTY=/dev/console``, but it still doesn't work, now I get ``gpg: signing failed: Permission denied``

Could we fix this somehow? Or better yet, is there a possibility to have these images with Ubuntu 16.04?

**Comment by amihaiemil** [comment]
@g4s8 Can you please have a look? :D

**Comment by g4s8** [comment]
@amihaiemil it seems you're using old Maven plugin with new GPG version, you can check how to update to fresh GPG plugin version here: https://github.com/g4s8/oot/blob/master/pom.xml#L229-L248
It's important to add `--pinentry-mode=loopback`:
```xml
                <configuration>
                  <gpgArguments>
                    <arg>--pinentry-mode</arg>
                    <arg>loopback</arg>
                  </gpgArguments>
                </configuration>
```

**Comment by amihaiemil** [comment]
@g4s8 Thanks a lot, it finally worked.
