### ISSUE TITLE
JDK11 Error while generating Javadoc

### ISSUE THREAD

**Issue by amihaiemil** [g4s8/dockers#2]
Hi @g4s8 

When using the jdk11 rultor image, I get the following error:

```
Error while generating Javadoc:
Unable to find javadoc command: The environment variable JAVA_HOME is not correctly
```

Although, from what I see [here](https://github.com/g4s8/dockers/blob/master/jdk-11/Dockerfile#L5), JAVA_HOME seems to be set.

Did you have this issue maybe? If yes, how did you fix it?

**Comment by g4s8** [comment]
@amihaiemil looks like `javadoc` is not exported by default to `$PATH`, so you either can call it explicitly `$JAVA_HOME/bin/javadoc` or export all java tools with `export PATH=$JAVA_HOME/bin:$HOME`

**Comment by amihaiemil** [comment]
@g4s8 I tried both options and none of them work. 
I tried ``echo ${JAVA_HOME}`` in my rultor script and it prints nothing: https://github.com/decorators-squad/eo-yaml/blob/master/.rultor.yml#L10

So apparently, it's not set at all...

**Comment by amihaiemil** [comment]
@g4s8 It finally worked when I specified JAVA_HOME manually: https://github.com/decorators-squad/eo-yaml/blob/master/.rultor.yml#L27

(I got the correct path from ``mvn --version``).
